seq_length: 49152
learning_rate: 5e-6
train_batch_size: 16
num_individuals_per_gene: 128
alpha: 0.5
experiment_name: "FinalPaperWholeBlood_MultiGPU_AllGenes_resume_0zioz3o7"
max_epochs: 150
precision: bf16-mixed
tissues_to_train: "Whole Blood"
gradient_clip_val: 0.05
seed: 0
n_gpus: 8
patience: 10
valid_metrics_save_freq: 2
monitor: mean_pearsonr_across_train_genes_across_valid_donors
train_ckpt_resume_path: /pollard/data/projects/sdrusinsky/enformer_fine_tuning/results/FinalPaperWholeBlood_MultiGPU_AllGenes/MultiGene/AllGenes/Fold-0/0zioz3o7/checkpoints/epoch=31-step=182784.ckpt